default: &default
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: storage/development.sqlite3

test:
  adapter: sqlite3
  database: storage/test.sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

production:
  primary:
    adapter: postgresql
    encoding: unicode
    pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
    url: <%= ENV["DATABASE_URL"] %>
  
  cache:
    adapter: postgresql
    url: <%= ENV["DATABASE_URL"] %>
  
  queue:
    adapter: postgresql
    url: <%= ENV["DATABASE_URL"] %>
  
  cable:
    adapter: postgresql
    url: <%= ENV["DATABASE_URL"] %>