default: &default
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: storage/development.sqlite3

test:
  <<: *default
  database: storage/test.sqlite3

production:
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  url: <%= ENV["DATABASE_URL"] %>

  cache:
    url: <%= ENV["DATABASE_URL"] %>
  queue:
    url: <%= ENV["DATABASE_URL"] %>
  cable:
    url: <%= ENV["DATABASE_URL"] %>